### ISSUE TITLE
The Switcher frequently breaks. Bookmarks from a group are half copied.

### ISSUE THREAD

**Issue by JohnLukeBentley** [Kapcash/bookmark-switcher#8]
As the title describes.

I don't have a clear reproduction path. Perhaps it occurs while switching is part way through a copy and you surf to a page?

**Comment by Kapcash** [comment]
Hi! Thank you for taking the time to report your issue here and I'm sorry you're facing it.

What version of Firefox do you currently use? And on what Operating System (OS)?
Are the bookmarks not copied always the same ones? If so, are they set as "pinned" on the popup? (Little blue pin icon on the bookmarks list).

Meanwhile I'm trying to identify any weak point in the switch part and try to improve it.

**Comment by JohnLukeBentley** [comment]
Firefox 105.0.1 (64-bit).
Windows 10 Pro; Version	21H2; OS build 19044.2006

I've never heard of ...
> If so, are they set as "pinned" on the popup? (Little blue pin icon on the bookmarks list).

.... and google doesn't give me a method to pin a bookmark. 

I'll lookout for a reproduction path.

Has the bookmark switching ever been flakey for you?

**Comment by Kapcash** [comment]
I'm talking about this feature from the extension:

<img width="331" alt="bookmark-switcher-pin" src="https://user-images.githubusercontent.com/10612835/192305188-e7697b9e-d636-4830-adb9-3fe7b2f3eaeb.png">

If you clicked on the pin, then the bookmark will stay in place on the bookmark bar and won't ever be switched between profiles.

It used to be flakey a long time ago on an old version, but this has been addressed. Since then, I've never experienced problems like yours.
If you can record the screen when the problem happens, I could try to understand what's wrong and reproduce :)

------

Also, I just published a new version (2.0.3) which fixes a bug when you use the keyboard shortcut while you have the popup opened. It caused the bars to mix up sometimes.

**Comment by JohnLukeBentley** [comment]
Thanks. 

So, indeed, I've never pinned the bookmarks.

Perhaps the keyboard shortcut bug, apparently unrelated, is the cause here too. I'll let you know if I ever get another mix up, even if I can't reproduce it.

**Comment by JohnLukeBentley** [comment]
Ok I can reproduce it.

* Create two bookmark groups, "Foo" and "Bar", and fill each with different bookmarks. Enough to cover the entire bar, or almost the entire bar (enough bookmarks to potentially get interrupted half way through the copy).
* Switch from one group to the other and, very quickly and before the copy has completed, click on any open tab (at the top).
* Observe a portion of bookmarks will be copied and your "foo" and "bar" will be mixed up.

This quick move to a tab after switching is something I evidently do as a matter of workflow. That is, it's not that I've hunted for a deliberately freakish edge case.

**Comment by Kapcash** [comment]
Perfect, thanks you for the reproduction steps!
I'll try to reproduce this locally and hopefully have a fix asap!

**Comment by Kapcash** [comment]
Hi @JohnLukeBentley 
I just deployed the version v2.0.4 which should fix your issue.

Basically, I ran the switching method from the popup process, which gets killed when it's being closed. So the switching method doesn't have time to finish properly.

It now always run from the background script, which cannot be interrupted :)

I let you close the issue if it's correctly fixed for you!

**Comment by JohnLukeBentley** [comment]
@Kapcash, you are a champion!

I've tested it and it seems solid. It's a good feeling to be able to use your very handy utility, now with the confidence it is unlikely to break.
