### ISSUE TITLE
Bug concering newly created Bars

### ISSUE THREAD

**Issue by ihithim** [Kapcash/bookmark-switcher#9]
When creating a new Bar, It doesnt seem able to switch to it until firefox is restarted. Clicking on other bars works correctly, but nothing happens when the new bar is selected

**Comment by ihithim** [comment]
Without restarting, I just entered the Manage Extension screen and enabled "Run In Private Mode", as i noticed I had some open private windows, and now all bars work correctly.

**Comment by Kapcash** [comment]
Hello @ihithim and thank you very much for taking the time to fill in this issue!

I just released the version v2.0.5 which resolves this issue. Please let me know if it's working better for you! I let you close the issue if that's the case :)

For the technical record: because we use twice the `useBookmarkBars()` composable (once in the popup and once in the background script), both bars refs are unsynced: when added to the popup ref, it's not reflected on the background script ref.
I added listeners so that when bookmarks folders are added / removed, all composables ref are updated (not just the "local" one)
